---
abstract: 'Just K markup language'
author:
  - 'tokuhirom <tokuhirom@gmail.com>'
build_requires:
  JSON::PP: 0
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.11.0, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: JKML
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
    - builder
provides:
  JKML:
    file: lib/JKML.pm
    version: 0.01
requires:
  Types::Serialiser: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/tokuhirom/JKML/issues
  homepage: https://github.com/tokuhirom/JKML
  repository: git://github.com/tokuhirom/JKML.git
version: 0.01
